version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"                    # 仓库根目录
    schedule:
      interval: "daily"               # 每天检查一次
      time: "04:00"                   # UTC 时间 04:00（中国时间中午12点）
    commit-message:
      prefix: "chore(deps)"           # 提交信息前缀
    labels:
      - "dependencies"
      - "submodules"
      - "auto-merge"                 # 用于触发自动合并
    open-pull-requests-limit: 10      # 最多同时打开 10 个子模块 PR

