repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: '\.(js|jsx|ts|tsx|json|css|md|yml|yaml)$'
        additional_dependencies:
          - prettier@3.3.3

  - repo: local
    hooks:
      - id: lint-check
        name: ESLint Check
        entry: npm run lint
        language: system
        pass_filenames: false

      - id: type-check
        name: TypeScript Type Check
        entry: npx tsc --noEmit
        language: system
        pass_filenames: false

      - id: parse-readme-check
        name: Check README Parser
        entry: npm run parse-readme
        language: system
        pass_filenames: false
