name: Dependabot auto-merge
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: read
  actions: read

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true
          
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for submodules
        if: ${{ steps.metadata.outputs.package-ecosystem == 'submodules' }}
        run: |
          echo "Attempting to auto-merge PR #${{ github.event.pull_request.number }}"
          echo "Package ecosystem: ${{ steps.metadata.outputs.package-ecosystem }}"
          echo "Update type: ${{ steps.metadata.outputs.update-type }}"
          
          # Use squash merge since rebase is disabled
          gh pr merge --squash --auto "${{ github.event.pull_request.number }}" || {
            echo "Auto-merge failed, checking status..."
            gh pr view "${{ github.event.pull_request.number }}" --json mergeStateStatus,mergeable
            exit 1
          }
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
